apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
spec:
  tls:
    - hosts:
      - keycloak.{{ keycloak.host_ip }}.nip.io
  rules:
  - host: keycloak.{{ keycloak.host_ip }}.nip.io
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: {{ keycloak.port }}
