apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: managed
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      # annotations:
      #   prometheus.io.scrape: "true"
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name:  node-exporter
        image: prom/node-exporter:v1.1.2
        imagePullPolicy: Never
        ports:
          - containerPort: 9100
            protocol: TCP
            name: http
            
            