apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: managed
  labels:
    app: node-exporter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.1.2
          imagePullPolicy: Never
          ports:
            - name: node-exporter
              containerPort: 9100
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - node-exporter
              topologyKey: "kubernetes.io/hostname"