---
- name: Copy namespace.yml
  template:
    src: namespace.yml
    dest: /home/vagrant

- name: Apply namespace
  command: kubectl apply -f /home/vagrant/namespace.yml
  register: namespace_applied

- name: Remove namespace.yml
  file:
    state: absent
    path: /home/vagrant/namespace.yml
  when: namespace_applied

- name: Copy deployment.yml
  template:
    src: deployment.yml
    dest: /home/vagrant

- name: Apply deployment
  command: kubectl apply -f /home/vagrant/deployment.yml
  register: deployment_applied

- name: Remove deployment.yml
  file:
    state: absent
    path: /home/vagrant/deployment.yml
  when: deployment_applied

- name: Copy service.yml
  template:
    src: service.yml
    dest: /home/vagrant

- name: Apply service
  command: kubectl apply -f /home/vagrant/service.yml
  register: service_applied

- name: Remove service.yml
  file:
    state: absent
    path: /home/vagrant/service.yml
  when: service_applied

- name: Copy ingress.yml
  template:
    src: ingress.yml
    dest: /home/vagrant

- name: Apply ingress
  command: kubectl apply -f /home/vagrant/ingress.yml
  register: ingress_applied

- name: Remove ingress.yml
  file:
    state: absent
    path: /home/vagrant/ingress.yml
  when: ingress_applied