---
# kubernetes 는 swap을 사용하지 않는다.
# 1. QoS(Qulity of Service) proposal과 상충된다.
# 2. Swap을 사용하면 Container의 성능을 예측할 수 없다.
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: isable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable swappiness and pass bridged IPv4 traffic to iptable's chains
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items:
    - { name: 'vm.swappiness', value: '0' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }

- name: Adding yum repository for kubernetes
  yum_repository:
    name: kubernetes
    description: description for kubernetes
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: no

- name: Install Kubernetes binaries
  yum:
    name: "{{ packages }}"
    state: installed
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Create service drop-in directory
  file:
    path: /etc/systemd/system/kubelet.service.d/
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Copy kubeadm conf to drop-in directory
  template: src=20-extra-args.conf.sample dest=/etc/systemd/system/kubelet.service.d/20-extra-args.conf

- name: Restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes

# Kubernetes master tasks
- name: Kubernetes master tasks
  include_tasks: "k8s-master.yml"
  when: is_master == true

# Kubernetes node tasks
- name: Kubernetes node tasks
  include_tasks: "k8s-node.yml"
  when: is_master != true



