---
- name: Install packges for pre-requires
  yum:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  vars:
    packages:
      - yum-utils
      - ca-certificates
      - device-mapper-persistent-data
      - lvm2
      

      