---
- name: Install mariadb
  hosts: k8s-master

  vars:
    mariadb_nodes: 
      - k8s-managed-1
    k8s:
      namespace: managed
      replicas: 1
    mariadb:
      user: admin
      password: admin
      host_ip: "{{ ansible_eth1.ipv4.address }}"
      port: 3306

  roles:
    - ./roles/install-mariadb