---
# kubernetes 는 swap을 사용하지 않는다.
# 1. QoS(Qulity of Service) proposal과 상충된다.
# 2. Swap을 사용하면 Container의 성능을 예측할 수 없다.
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Add an apt signing key for kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Kubernetes binaries
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet
      - kubeadm
      - kubectl

- name: Configure node IP
  lineinfile:
    # https://stackoverflow.com/questions/56998761/using-vagrant-ansible-to-spin-up-a-multi-node-kubernetes-cluster-fails-detecting/56999004
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}


- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted