kubernetes:
  hosts:
    k8s-master:
      ansible_host: 172.16.0.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    k8s-managed-1:
      ansible_host: 172.16.0.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    k8s-worker-1:
      ansible_host: 172.16.0.21
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key