kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb
  labels:
    type: local
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/vm_data/mariadb"