apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ k8s.namespace }}
  labels:
    app: keycloak
spec:
  replicas: {{ k8s.replicas }}
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:12.0.4
        env:
        - name: KEYCLOAK_USER
          value: {{ keycloak.user }}
        - name: KEYCLOAK_PASSWORD
          value: {{ keycloak.password }}
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080
    # affinity:
    #   pod